import { checkCookies, getCookie, getCookies } from "cookies-next";
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Home from '../pages/Home'


export default function Index() {
    return (
        <div className={styles.container}>
            <Head>
                <title>revere labs</title>
                <meta name="description"
                    content="Generated by create next app" />
                <link rel="icon"
                    href="/favicon.ico" />
            </Head>
            <Home/>
        </div>
    )
}

// export async function getServerSideProps({ req, res }) {
//   try {
//     const cookieExists = getCookie("token", { req, res });
//     console.log(cookieExists);
//     if (cookieExists) return { redirect: { destination: "/login" } };
//     return { props: {} };
//   } catch (err) {
//     return { props: {} };
//   }
// }


