import { checkCookies, getCookie, getCookies } from "cookies-next";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SearchBar from '../components/SearchBar'
import FilterButton from '../components/FilterButton'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>revere labs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="fixed top-[10vh] left-[-5rem]"><Image src="/background/bg1.png" height="500" width="415" /></div>
      <div className="fixed top-[55vh] bottom-0 right-0"><Image src="/background/bg2.png" height="480" width="670" /></div>

      <div className="flex w-[100%] h-[20vh] items-center justify-between">
        <SearchBar/>
        <FilterButton/>
      </div>

      <div>


      </div>


    </div>
  )
}

// export async function getServerSideProps({ req, res }) {
//   try {
//     const cookieExists = getCookie("token", { req, res });
//     console.log(cookieExists);
//     if (cookieExists) return { redirect: { destination: "/login" } };
//     return { props: {} };
//   } catch (err) {
//     return { props: {} };
//   }
// }


